export const mockBookings = [
    {
        id: "BK-1001",
        userId: "USR-001",
        userName: "John Doe",
        roomId: 1,
        roomName: "Conference Room A",
        date: "2026-02-05",
        startTime: "09:00",
        time: "09:00",
        durationHours: 2,
        guests: 4,
        status: "confirmed",
        notes: ""
    },
    {
        id: "BK-1002",
        userId: "USR-002",
        userName: "Jane Smith",
        roomId: 2,
        roomName: "Meeting Room B",
        date: "2026-02-05",
        startTime: "10:00",
        time: "10:00",
        durationHours: 1,
        guests: 2,
        status: "confirmed",
        notes: ""
    },
    {
        id: "BK-1003",
        userId: "USR-003",
        userName: "Mike Johnson",
        roomId: 1,
        roomName: "Conference Room A",
        date: "2026-02-06",
        startTime: "14:00",
        time: "14:00",
        durationHours: 3,
        guests: 6,
        status: "pending",
        notes: "Team planning session"
    },
    {
        id: "BK-1004",
        userId: "USR-004",
        userName: "Sarah Lee",
        roomId: 3,
        roomName: "Private Office 1",
        date: "2026-02-07",
        startTime: "08:00",
        time: "08:00",
        durationHours: 4,
        guests: 1,
        status: "confirmed",
        notes: ""
    },
    {
        id: "BK-1005",
        userId: "USR-005",
        userName: "Tom Wilson",
        roomId: 2,
        roomName: "Meeting Room B",
        date: "2026-02-08",
        startTime: "15:00",
        time: "15:00",
        durationHours: 2,
        guests: 3,
        status: "cancelled",
        notes: "Cancelled by user"
    },
    {
        id: "BK-1006",
        userId: "USR-006",
        userName: "Emily Chen",
        roomId: 4,
        roomName: "Hot Desk Area",
        date: "2026-02-10",
        startTime: "09:00",
        time: "09:00",
        durationHours: 8,
        guests: 1,
        status: "confirmed",
        notes: ""
    },
    {
        id: "BK-1007",
        userId: "USR-007",
        userName: "David Park",
        roomId: 5,
        roomName: "Event Space",
        date: "2026-02-12",
        startTime: "13:00",
        time: "13:00",
        durationHours: 5,
        guests: 20,
        status: "pending",
        notes: "Company event"
    },
    {
        id: "BK-1008",
        userId: "USR-008",
        userName: "Lisa Brown",
        roomId: 1,
        roomName: "Conference Room A",
        date: "2026-02-15",
        startTime: "11:00",
        time: "11:00",
        durationHours: 2,
        guests: 5,
        status: "confirmed",
        notes: ""
    },
    {
        id: "BK-1009",
        userId: "USR-009",
        userName: "Chris Taylor",
        roomId: 3,
        roomName: "Private Office 1",
        date: "2026-02-18",
        startTime: "10:00",
        time: "10:00",
        durationHours: 3,
        guests: 1,
        status: "completed",
        notes: ""
    },
    {
        id: "BK-1010",
        userId: "USR-010",
        userName: "Amy Garcia",
        roomId: 2,
        roomName: "Meeting Room B",
        date: "2026-02-20",
        startTime: "16:00",
        time: "16:00",
        durationHours: 1,
        guests: 4,
        status: "confirmed",
        notes: "Quick standup"
    }
];
